---
# tasks file for apache
- name: instalamos paquetes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_packages }}"

- name: levantamos el servicio apache
  service:
    name: "{{ apache_service}}"
    state: started
    enabled: yes
  notify: "reinicia httpd"
- name: cree pagina bienvenida por defecto
  copy:
    src: index.html
    dest: /var/www/html/index.html
  notify: "reinicia httpd"
