---
- hosts: "{{ servidores }}"
  become: true
  tasks:
  - name: crea usuario 
    user:
     name: "{{ usuarios.nombre }}"
     groups: "{{ usuarios.grupo }}"
     shell: "/bin/bash"
     comment: "usuario creado por Ansible"
     state: present
    whit_items: "{{ usuarios }}"
    